PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
Update Playbook Swift version.
- [[Runway Story]](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-250)
[Yes/No (Explain)]
[Insert testing details or N/A]
=> Release 4.9.0

PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-262] 4.10.0-release

Jenkinsfile, Tools/github-utils.sh, portal.yml
=> [PBIOS-281] Rename project repo

Sources/Playbook/Components/User/Multiple Users Stacked/PBMultipleUsersStacked.swift, Sources/Playbook/Components/User/Multiple Users/PBMultipleUsers.swift, Sources/Playbook/Components/User/PBUser.swift, Sources/Playbook/Components/User/UserCatalog.swift
Fix subtitle prop to conform to AnyView type.
1. Go to Components -> User 
2.  Scroll down to 'clock content subtitle'
=> [PBIOS-290] Fix subtitle prop

PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-273] 4.11.0-release

Sources/Playbook/Components/Date/DateCatalog.swift, Sources/Playbook/Components/Date/PBDate.swift
[PBIOS-300]RemoveYearFromDateKitWhenCurrent
1. Go to '...'
=> [PBIOS-300]RemoveYearFromDateKitWhenCurrent

Sources/Playbook/Components/Date Range Inline/DateRangeInlineCatalog.swift, Sources/Playbook/Components/Date Range Inline/PBDateRangeInline.swift, Sources/Playbook/Components/Date Time/DateTimeCatalog.swift, Sources/Playbook/Components/Date/DateCatalog.swift, Sources/Playbook/Components/Date/PBDate.swift, Sources/Playbook/Resources/Helper Files/Components.swift
[PBIOS-307] Date Range Inline Kit
**Screenshots:** 
1. Go to '...'
=> [PBIOS-307] Date Range Inline Kit

Sources/Playbook/Components/Avatar/docs/_avatar_default_swift.md, Sources/Playbook/Components/Avatar/docs/_avatar_monogram_swift.md, Sources/Playbook/Components/Avatar/docs/_avatar_props_swift.md, Sources/Playbook/Components/Avatar/docs/example.yml
[PBIOS-320] Avatar Docs
1. Go to '...'
=> [PBIOS-320] Avatar Docs

Sources/Playbook/Components/Badge/docs/_badge_colors_swift.md, Sources/Playbook/Components/Badge/docs/_badge_default_swift.md, Sources/Playbook/Components/Badge/docs/_badge_notification_swift.md, Sources/Playbook/Components/Badge/docs/_badge_props_swift.md, Sources/Playbook/Components/Badge/docs/_badge_rounded_swift.md, Sources/Playbook/Components/Badge/docs/example.yml
[PBIOS-322] Badge Docs
1. Go to '...'
=> [PBIOS-322] Badge Docs

Sources/Playbook/Components/Button/docs/_button_circle_swift.md, Sources/Playbook/Components/Button/docs/_button_default_swift.md, Sources/Playbook/Components/Button/docs/_button_full_width_swift.md, Sources/Playbook/Components/Button/docs/_button_icon_options_swift.md, Sources/Playbook/Components/Button/docs/_button_props_swift.md, Sources/Playbook/Components/Button/docs/_button_reaction_swift.md, Sources/Playbook/Components/Button/docs/_button_size_swift.md, Sources/Playbook/Components/Button/docs/example.yml
[PBIOS-323] Button Docs
1. Go to '...'
=> [PBIOS-323] Button Docs

Sources/Playbook/Components/Card/docs/_card_background_swift.md, Sources/Playbook/Components/Card/docs/_card_border_none_swift.md, Sources/Playbook/Components/Card/docs/_card_border_radius_swift.md, Sources/Playbook/Components/Card/docs/_card_header_swift.md, Sources/Playbook/Components/Card/docs/_card_highlight_swift.md, Sources/Playbook/Components/Card/docs/_card_light_swift.md, Sources/Playbook/Components/Card/docs/_card_padding_swift.md, Sources/Playbook/Components/Card/docs/_card_props_swift.md, Sources/Playbook/Components/Card/docs/_card_separator_swift.md, Sources/Playbook/Components/Card/docs/_card_shadow_swift.md, Sources/Playbook/Components/Card/docs/_card_styles_swift.md, Sources/Playbook/Components/Card/docs/example.yml
[PBIOS-324] Card Docs
1. Go to '...'
=> [PBIOS-324] Card Docs

Sources/Playbook/Components/Checkbox/docs/_checkbox_default_swift.md, Sources/Playbook/Components/Checkbox/docs/_checkbox_error_swift.md, Sources/Playbook/Components/Checkbox/docs/_checkbox_indeterminate_swift.md, Sources/Playbook/Components/Checkbox/docs/_checkbox_props_swift.md, Sources/Playbook/Components/Checkbox/docs/example.yml
[PBIOS-326] Checkbox Docs
1. Go to '...'
=> [PBIOS-326] Checkbox Docs

Sources/Playbook/Components/Date/docs/_ date_unstyled_swift.md, Sources/Playbook/Components/Date/docs/_date_alignment_swift.md, Sources/Playbook/Components/Date/docs/_date_default_swift.md, Sources/Playbook/Components/Date/docs/_date_props_swift.md, Sources/Playbook/Components/Date/docs/_date_variants_swift.md, Sources/Playbook/Components/Date/docs/example.yml
[PBIOS-330] Date Docs
1. Go to '...'
=> [PBIOS-330] Date Docs

Sources/Playbook/Components/Date Stacked/docs/_date_stacked_bold_swift.md, Sources/Playbook/Components/Date Stacked/docs/_date_stacked_default_swift.md, Sources/Playbook/Components/Date Stacked/docs/_date_stacked_not_current_year_swift.md, Sources/Playbook/Components/Date Stacked/docs/_date_stacked_props_swift.md, Sources/Playbook/Components/Date Stacked/docs/_date_stacked_reversed_swift.md, Sources/Playbook/Components/Date Stacked/docs/_date_stacked_sizes_swift.md, Sources/Playbook/Components/Date Stacked/docs/example.yml
[PBIOS-335] Date Stacked Docs
1. Go to '...'
=> [PBIOS-335] Date Stacked Docs

Sources/Playbook/Components/Contact/docs/_contact_default_swift.md, Sources/Playbook/Components/Contact/docs/_contact_props_swift.md, Sources/Playbook/Components/Contact/docs/_contact_with_detail_swift.md, Sources/Playbook/Components/Contact/docs/example.yml
[PBIOS-329] Contact Docs
1. Go to '...'
=> [PBIOS-329] Contact Docs

Sources/Playbook/Components/Date Range Inline/docs/_date_range_inline_default_swift.md, Sources/Playbook/Components/Date Range Inline/docs/_date_range_inline_props_swift.md, Sources/Playbook/Components/Date Range Inline/docs/example.yml
[PBIOS-331] Date Range Inline Docs
1. Go to '...'
=> [PBIOS-331] Date Range Inline Docs

Sources/Playbook/Components/Date Year Stacked/docs/_date_stacked_props_swift:.md, Sources/Playbook/Components/Date Year Stacked/docs/_date_year_stacked_default_swift.md, Sources/Playbook/Components/Date Year Stacked/docs/example.yml
[PBIOS-340] Date Year Stacked Docs
1. Go to '...'
=> [PBIOS-340] Date Year Stacked Docs

PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-312] 4.13.0-release

Sources/Playbook/Components/Currency/docs/_currency_size_swift.md, Sources/Playbook/Components/Date Range Inline/docs/_date_range_inline_default_swift.md, Sources/Playbook/Components/Date Range Stacked/docs/_date_range_stacked_default_swift.md, Sources/Playbook/Components/Date Stacked/docs/_date_stacked_bold_swift.md, Sources/Playbook/Components/Date Stacked/docs/_date_stacked_default_swift.md, Sources/Playbook/Components/Date Stacked/docs/_date_stacked_not_current_year_swift.md, Sources/Playbook/Components/Date Stacked/docs/_date_stacked_reversed_swift.md, Sources/Playbook/Components/Date Time/docs/_dateTime_alignment_swift.md, Sources/Playbook/Components/Date Time/docs/_dateTime_default_swift.md, Sources/Playbook/Components/Date Time/docs/_dateTime_size_swift.md, Sources/Playbook/Components/Date Year Stacked/docs/_date_year_stacked_default_swift.md
=> [PBIOS-342] Doc Screenshots

Sources/Playbook/Components/Dialog/docs/_dialog_default_swift.md, Sources/Playbook/Components/Dialog/docs/_dialog_props_swift.md, Sources/Playbook/Components/Dialog/docs/_dialog_sizes_swift.md, Sources/Playbook/Components/Dialog/docs/_dialog_stacked_swift.md, Sources/Playbook/Components/Dialog/docs/_dialog_status_swift.md, Sources/Playbook/Components/Dialog/docs/example.yml
[PBIOS-344] Dialog Docs
1. Go to '...'
=> [PBIOS-344] Dialog Docs

Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_children_swift.md, Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_close_swift.md, Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_default_swift.md, Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_dismiss_with_timer_swift.md, Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_multi_line_swift.md, Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_positions_swift.md, Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_props_swift.md, Sources/Playbook/Components/Fixed Confirmation Toast/docs/example.yml
[PBIOS-349] Confirmation Toast Docs
=> [PBIOS-349] Confirmation Toast Docs

Sources/Playbook/Components/Message/MessageCatalog.swift, Sources/Playbook/Components/Message/PBMessage.swift, Sources/Playbook/Resources/Helper Files/Mocks.swift
[PBIOS-341] Message Loading Variant
=> [PBIOS-341] Message Loading Variant

PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-355] 4.14.0-release

Sources/Playbook/Components/Message/MessageCatalog.swift, Sources/Playbook/Components/Message/PBMessage.swift
[PBIOS-357]Fix Message Loading Timestamp
=> [PBIOS-357] Fix Message Loading Timestamp

PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-358] 4.14.1-release

Sources/Playbook/Components/Button/PBButton.swift, Sources/Playbook/Components/Loader/LoaderCatalog.swift, Sources/Playbook/Components/Loader/PBLoader.swift
[PBIOS-352] Solid Loader Variant
=> [PBIOS-352] Solid Loader Variant

Sources/Playbook/Components/Home Address Street/docs/_home_street_address_default_swift.md, Sources/Playbook/Components/Home Address Street/docs/_home_street_address_emphasis_swift.md, Sources/Playbook/Components/Home Address Street/docs/_home_street_address_link_swift.md, Sources/Playbook/Components/Home Address Street/docs/_home_street_address_modified_swift.md, Sources/Playbook/Components/Home Address Street/docs/_home_street_address_props_swift.md, Sources/Playbook/Components/Home Address Street/docs/example.yml
[PBIOS-368] Home Street Address Docs
=> [PBIOS-368] Home Street Address Docs

Sources/Playbook/Components/Image/docs/_image_default_swift.md, Sources/Playbook/Components/Image/docs/_image_props_swift.md, Sources/Playbook/Components/Image/docs/_image_rounded_swift.md, Sources/Playbook/Components/Image/docs/example.yml
=> [PBIOS-371] Image Docs

Sources/Playbook/Components/Label Value/docs/_label_value_default_swift.md, Sources/Playbook/Components/Label Value/docs/_label_value_details_swift.md, Sources/Playbook/Components/Label Value/docs/_label_value_other_examples_swift.md, Sources/Playbook/Components/Label Value/docs/_label_value_props_swift.md, Sources/Playbook/Components/Label Value/docs/example.yml
=> [PBIOS-375] Label Value Docs

PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-348] 4.15.0-release

Sources/Playbook/Components/Nav/docs/_nav_horizontal_bold_swift.md, Sources/Playbook/Components/Nav/docs/_nav_horizontal_default_swift.md, Sources/Playbook/Components/Nav/docs/_nav_horizontal_subtle_no_highlight_swift.md, Sources/Playbook/Components/Nav/docs/_nav_horizontal_subtle_swift.md, Sources/Playbook/Components/Nav/docs/_nav_vertical_bold_swift.md, Sources/Playbook/Components/Nav/docs/_nav_vertical_default_swift.md, Sources/Playbook/Components/Nav/docs/_nav_vertical_subtle_no_highlight_swift.md, Sources/Playbook/Components/Nav/docs/_nav_vertical_subtle_swift.md, Sources/Playbook/Components/Person Contact/docs/_person_contact_default_swift.md, Sources/Playbook/Components/Person Contact/docs/_person_contact_multiple_people_swift.md, Sources/Playbook/Components/Person Contact/docs/_person_contact_with_wrong_numbers_swift.md
[PBIOS-399] Nav Person Contact Docs
=> [PBIOS-399] Nav + Person Contact doc screenshots

Sources/Playbook/Components/User/Multiple Users Stacked/docs/_multiple_users_stacked_default_swift.md, Sources/Playbook/Components/User/Multiple Users Stacked/docs/_multiple_users_stacked_extra_small_swift.md, Sources/Playbook/Components/User/Multiple Users Stacked/docs/_multiple_users_stacked_props_swift.md, Sources/Playbook/Components/User/Multiple Users Stacked/docs/_multiple_users_stacked_small_swift.md, Sources/Playbook/Components/User/Multiple Users Stacked/docs/example.yml
[PBIOS-421] Multiple Users Stacked Docs
=> [PBIOS-421] Multiple Users Stacked Docs

PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-411] 5.1.0-release

Sources/Playbook/Components/Message/MessageCatalog.swift, Sources/Playbook/Design Elements/Colors/Color.xcassets/Status/Neutral.colorset/Contents.json, Sources/Playbook/Design Elements/Colors/Color.xcassets/Status/Warning.colorset/Contents.json
[PBIOS-440] Pill Kit Color Validation
=> [PBIOS-440] Pill Kit Color Validation

PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-463] 6.0.2-release

Sources/Playbook/Components/Online Status/OnlineStatusCatalog.swift, Sources/Playbook/Components/Online Status/PBOnlineStatus.swift
Review Online Status kit
1. Go to '...'
=> [PBIOS-468] Online Status kit code review

Changelog.md, PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-562] 6.3.0-release

Changelog.md, PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-595] 6.4.0-release

Sources/Playbook/Components/Typeahead/PBTypeahead.swift, Sources/Playbook/Components/Typeahead/PBTypeaheadTemplate.swift, Sources/Playbook/Components/Typeahead/Typeahead.swift, Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift, Sources/Playbook/Resources/Helper Files/Mocks.swift
Show a highlight on the selected item when the list is opened in single-select mode when the list has a pre selected value.
1. Go to '...'
=> [PBIOS-598] Fix single selection highlight

Changelog.md, PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-600] 6.5.0-release

Sources/Playbook/Components/Typeahead/PBTypeahead.swift, Sources/Playbook/Components/Typeahead/PBTypeaheadTemplate.swift, Sources/Playbook/Components/Typeahead/Typeahead.swift, Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift, Sources/Playbook/Resources/Helper Files/Mocks.swift
This has necessary changes to Connect app use Playbook 6.5.0.
1. Go to '...'
=> [ROGUE-1665] 6.5.0 necessary changes

Changelog.md, PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, Sources/Playbook/Components/Typeahead/PBTypeaheadTemplate.swift, Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift, project.yml
=> [PBIOS-637] 6.6.0-release

Changelog.md, PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-657] 6.6.1-release

Sources/Playbook/Components/Popover/PopoverCatalog.swift, Sources/Playbook/Components/Popover/PopoverExploration.swift, Sources/Playbook/Components/Popover/PopoverHandler.swift, Sources/Playbook/Components/Popover/PopoverManager.swift
=> [PBIOS-522] Add popover activity flag

Sources/Playbook/Components/Button/ButtonsCatalog.swift, Sources/Playbook/Components/Button/PBReactionButton.swift
[PBIOS-671] Fix Reaction Button Font Color Alignment
=> [PBIOS-671] Fix Reaction Button Font Color Alignment

.github/workflows/stale.yml, Changelog.md, PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-672] 6.6.3-release

Gemfile, Gemfile.lock, PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj
**What does this PR do?** Update to profile managed by iOS provisioning profile repository.
Task on Runway [RANGR-878](https://nitro.powerhrg.com/runway/backlog_items/RANGR-878).
1. Go to '...'
=> [RANGR-878] Update to profile managed by iOS provisiong profile repository

Changelog.md, PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-654] 6.7.0-release

Jenkinsfile, fastlane/Fastfile
Task on Runway [RANGR-923](https://nitro.powerhrg.com/runway/backlog_items/RANGR-923).
In this PR, I am adding the upload of the iOS and macOS files to Nitro MDM. This is so we can replace AppCenter with Nitro App Portal.
=> [RANGR-923] Adding Nitro MDM script

Tools/keychain.sh, fastlane/Fastfile
Task on Runway [RANGR-962](https://nitro.powerhrg.com/runway/backlog_items/RANGR-962).
=> [RANGR-962] Update to new certificate and profile type

Tools/keychain.sh
Task on Runway [RANGR-981](https://nitro.powerhrg.com/runway/backlog_items/RANGR-981).
=> [RANGR-981] Update macOS certificate

Changelog.md, PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-1027] 6.10.0-release

renovate.json
Some of these proposed updates are mandatory for continued functionality, like ci-kubed v9.0.0 was needed for playbook-ui and Huddle.
=> Renovate should propose major upgrades

Changelog.md, PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-1055] 6.10.1-release

PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, project.yml
=> [PBIOS-2080] 6.11.0-release

PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj, Sources/Playbook/Components/Nav/PBNavItem.swift, Sources/Playbook/Components/Tab Bar/PBTabBar.swift, Sources/Playbook/Components/User/Multiple Users Indicator/PBMultipleUsersIndicator.swift, project.yml
Adjust other shadow color usages
=> [ROGUE-2066] Fix other Shadow color usage

PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj
=> [PBIOS-2080] 6.11.1-release
